language: java 
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/modules-2/files-2.1


before_install:
- chmod a+x gradlew
- chmod a+x gradle/wrapper/gradle-wrapper.jar

# Deployment to GitHub-releases
build:
  - ./gradlew dockerBuild
# add coverage and integration tests
