language: java 
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/modules-2/files-2.1


before_install:
- chmod a+x gradlew
- chmod a+x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew build
  - ./gradlew jacocoTestReport
  - ./gradlew dockerBuild
after_success:
  - bash <(curl -s https://codecov.io/bash)