version: '3'

services: 
  cities-registry:
    build: 
      context: ./cities-registry
    ports:
      - 8444:8444
    networks:
      - net1
  route-calculator:
    build:
      context: ./route-calculator
    ports:
      - 8443:8443
    environment:
      - CITIES_REGISTRY_URL=https://cities-registry:8444
    depends_on:
      - cities-registry
    networks:
      - net1

networks:
  net1:
    driver: bridge